2023-09-05 21:34:22,759 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-05 21:34:22,775 INFO supervisord started with pid 1
2023-09-05 21:34:23,779 INFO spawned: 'celery' with pid 9
2023-09-05 21:34:23,782 INFO spawned: 'flask' with pid 10
2023-09-05 21:34:24,389 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139937443071472 for <Subprocess at 139937443071112 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-05 21:34:24,804 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-05 21:34:24,804 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-05 21:35:04,753 WARN received SIGTERM indicating exit request
2023-09-05 21:35:04,753 INFO waiting for celery, flask to die
2023-09-05 21:35:04,754 INFO stopped: flask (terminated by SIGTERM)
2023-09-05 21:35:06,700 INFO stopped: celery (exit status 0)
2023-09-05 21:35:55,508 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-05 21:35:55,510 INFO supervisord started with pid 1
2023-09-05 21:35:56,515 INFO spawned: 'celery' with pid 8
2023-09-05 21:35:56,517 INFO spawned: 'flask' with pid 9
2023-09-05 21:35:56,983 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140170494076400 for <Subprocess at 140170494076040 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-05 21:35:58,322 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-05 21:35:58,322 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-05 23:09:44,708 WARN received SIGTERM indicating exit request
2023-09-05 23:09:44,970 INFO waiting for celery, flask to die
2023-09-05 23:09:44,976 INFO stopped: flask (terminated by SIGTERM)
2023-09-05 23:09:47,397 INFO stopped: celery (exit status 0)
2023-09-05 23:09:48,360 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-05 23:09:48,362 INFO supervisord started with pid 1
2023-09-05 23:09:49,366 INFO spawned: 'celery' with pid 10
2023-09-05 23:09:49,368 INFO spawned: 'flask' with pid 11
2023-09-05 23:09:49,878 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140021790537200 for <Subprocess at 140021790536840 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-05 23:09:51,225 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-05 23:09:51,226 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-05 23:13:40,945 WARN received SIGTERM indicating exit request
2023-09-05 23:13:40,945 INFO waiting for celery, flask to die
2023-09-05 23:13:40,948 INFO stopped: flask (terminated by SIGTERM)
2023-09-05 23:13:42,829 INFO stopped: celery (exit status 0)
2023-09-05 23:18:21,164 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-05 23:18:21,272 INFO supervisord started with pid 1
2023-09-05 23:18:22,277 INFO spawned: 'celery' with pid 9
2023-09-05 23:18:22,279 INFO spawned: 'flask' with pid 10
2023-09-05 23:18:23,231 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140571708823024 for <Subprocess at 140571708822664 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-05 23:18:23,812 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-05 23:18:23,812 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 09:08:46,305 WARN received SIGTERM indicating exit request
2023-09-06 09:08:46,305 INFO waiting for celery, flask to die
2023-09-06 09:08:46,307 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 09:08:47,937 INFO stopped: celery (exit status 0)
2023-09-06 09:08:48,721 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 09:08:48,723 INFO supervisord started with pid 1
2023-09-06 09:08:49,728 INFO spawned: 'celery' with pid 9
2023-09-06 09:08:49,730 INFO spawned: 'flask' with pid 10
2023-09-06 09:08:50,201 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139667865495024 for <Subprocess at 139667865494664 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:08:51,565 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 09:08:51,566 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 09:38:27,047 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139667865495024 for <Subprocess at 139667865494664 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:38:27,058 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139667865495024 for <Subprocess at 139667865494664 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:40:12,887 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139667865495024 for <Subprocess at 139667865494664 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:40:12,888 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139667865495024 for <Subprocess at 139667865494664 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:45:01,569 WARN received SIGTERM indicating exit request
2023-09-06 09:45:01,569 INFO waiting for celery, flask to die
2023-09-06 09:45:01,572 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 09:45:03,516 INFO stopped: celery (exit status 0)
2023-09-06 09:47:00,111 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 09:47:00,113 INFO supervisord started with pid 1
2023-09-06 09:47:01,117 INFO spawned: 'celery' with pid 9
2023-09-06 09:47:01,120 INFO spawned: 'flask' with pid 10
2023-09-06 09:47:01,594 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140061198865904 for <Subprocess at 140061198865544 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:47:02,954 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 09:47:02,954 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 09:47:09,635 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140061198865904 for <Subprocess at 140061198865544 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:47:09,747 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140061198865904 for <Subprocess at 140061198865544 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:48:06,713 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140061198865904 for <Subprocess at 140061198865544 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 09:48:36,119 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140061198865904 for <Subprocess at 140061198865544 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 12:29:58,576 WARN received SIGTERM indicating exit request
2023-09-06 12:29:58,576 INFO waiting for celery, flask to die
2023-09-06 12:29:58,578 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 12:30:00,519 INFO stopped: celery (exit status 0)
2023-09-06 12:30:14,705 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 12:30:14,707 INFO supervisord started with pid 1
2023-09-06 12:30:15,712 INFO spawned: 'celery' with pid 9
2023-09-06 12:30:15,715 INFO spawned: 'flask' with pid 10
2023-09-06 12:30:15,830 WARN received SIGTERM indicating exit request
2023-09-06 12:30:15,830 INFO waiting for celery, flask to die
2023-09-06 12:30:15,831 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 12:30:15,832 INFO stopped: celery (terminated by SIGTERM)
2023-09-06 12:31:13,119 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 12:31:13,121 INFO supervisord started with pid 1
2023-09-06 12:31:14,125 INFO spawned: 'celery' with pid 9
2023-09-06 12:31:14,128 INFO spawned: 'flask' with pid 10
2023-09-06 12:31:14,594 CRIT uncaptured python exception, closing channel <POutputDispatcher at 139964608353776 for <Subprocess at 139964608353416 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 12:31:15,964 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 12:31:15,965 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 12:39:08,621 WARN received SIGTERM indicating exit request
2023-09-06 12:39:08,621 INFO waiting for celery, flask to die
2023-09-06 12:39:08,629 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 12:39:10,423 INFO stopped: celery (exit status 0)
2023-09-06 12:39:38,845 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 12:39:38,847 INFO supervisord started with pid 1
2023-09-06 12:39:39,851 INFO spawned: 'celery' with pid 8
2023-09-06 12:39:39,854 INFO spawned: 'flask' with pid 9
2023-09-06 12:39:40,318 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140502242928112 for <Subprocess at 140502242927752 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 12:39:41,656 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 12:39:41,656 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 12:49:09,205 WARN received SIGTERM indicating exit request
2023-09-06 12:49:09,205 INFO waiting for celery, flask to die
2023-09-06 12:49:09,210 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 12:49:11,118 INFO stopped: celery (exit status 0)
2023-09-06 12:52:04,332 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 12:52:04,334 INFO supervisord started with pid 1
2023-09-06 12:52:05,338 INFO spawned: 'celery' with pid 9
2023-09-06 12:52:05,341 INFO spawned: 'flask' with pid 10
2023-09-06 12:52:05,810 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140191642531312 for <Subprocess at 140191642530952 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 12:52:07,152 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 12:52:07,152 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 12:57:50,452 WARN received SIGTERM indicating exit request
2023-09-06 12:57:50,452 INFO waiting for celery, flask to die
2023-09-06 12:57:50,454 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 12:57:52,997 INFO stopped: celery (exit status 0)
2023-09-06 12:58:18,418 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 12:58:18,420 INFO supervisord started with pid 1
2023-09-06 12:58:19,425 INFO spawned: 'celery' with pid 9
2023-09-06 12:58:19,427 INFO spawned: 'flask' with pid 10
2023-09-06 12:58:19,894 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140233776182768 for <Subprocess at 140233776182408 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 12:58:21,239 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 12:58:21,240 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 12:59:25,044 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140233776182768 for <Subprocess at 140233776182408 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 15:04:26,406 WARN received SIGTERM indicating exit request
2023-09-06 15:04:26,406 INFO waiting for celery, flask to die
2023-09-06 15:04:26,408 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 15:04:28,654 INFO stopped: celery (exit status 0)
2023-09-06 15:04:53,202 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 15:04:53,204 INFO supervisord started with pid 1
2023-09-06 15:04:54,206 INFO spawned: 'celery' with pid 9
2023-09-06 15:04:54,207 INFO spawned: 'flask' with pid 10
2023-09-06 15:04:54,668 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140009023636976 for <Subprocess at 140009023636616 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 15:04:55,824 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 15:04:55,824 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 15:04:57,393 WARN received SIGTERM indicating exit request
2023-09-06 15:04:57,393 INFO waiting for celery, flask to die
2023-09-06 15:04:57,395 INFO stopped: flask (terminated by SIGTERM)
2023-09-06 15:04:59,724 INFO stopped: celery (exit status 0)
2023-09-06 15:12:18,313 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-06 15:12:18,334 INFO supervisord started with pid 1
2023-09-06 15:12:19,338 INFO spawned: 'celery' with pid 8
2023-09-06 15:12:19,341 INFO spawned: 'flask' with pid 9
2023-09-06 15:12:19,861 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-06 15:12:21,191 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-06 15:12:21,191 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-07 20:29:18,749 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 20:29:18,781 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 20:30:27,746 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:05:18,480 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:07:31,541 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:10:56,837 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:18:54,403 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:24:12,743 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:37:48,471 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:53:46,806 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:53:46,885 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 21:57:28,235 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 22:03:07,854 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 22:05:31,440 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-07 22:05:48,624 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 10:17:19,490 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 10:37:08,613 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 10:48:54,201 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 10:48:57,024 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140714614253040 for <Subprocess at 140714614252680 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 11:54:17,742 WARN received SIGTERM indicating exit request
2023-09-08 11:54:17,745 INFO waiting for celery, flask to die
2023-09-08 11:54:17,748 INFO stopped: flask (terminated by SIGTERM)
2023-09-08 11:54:19,675 INFO stopped: celery (exit status 0)
2023-09-08 11:54:33,473 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-08 11:54:33,510 INFO supervisord started with pid 1
2023-09-08 11:54:34,512 INFO spawned: 'celery' with pid 9
2023-09-08 11:54:34,514 INFO spawned: 'flask' with pid 10
2023-09-08 11:54:35,018 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140066158278128 for <Subprocess at 140066158277768 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 11:54:36,384 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-08 11:54:36,384 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-08 11:55:03,789 WARN received SIGTERM indicating exit request
2023-09-08 11:55:03,789 INFO waiting for celery, flask to die
2023-09-08 11:55:03,791 INFO stopped: flask (terminated by SIGTERM)
2023-09-08 11:55:05,517 INFO stopped: celery (exit status 0)
2023-09-08 14:18:16,825 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-08 14:18:16,827 INFO supervisord started with pid 1
2023-09-08 14:18:17,831 INFO spawned: 'celery' with pid 9
2023-09-08 14:18:17,834 INFO spawned: 'flask' with pid 10
2023-09-08 14:18:18,298 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state STARTING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:18:19,634 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-08 14:18:19,635 INFO success: flask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-09-08 14:25:56,690 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:25:56,798 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:26:19,413 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:43:31,992 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:43:33,237 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:46:33,280 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:46:36,230 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:48:22,415 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:53:41,841 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:56:07,932 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-08 14:57:29,616 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-16 18:13:16,587 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-16 18:31:54,717 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-16 18:56:39,424 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-17 14:29:00,877 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-17 15:45:48,635 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-17 16:02:31,508 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-17 16:04:24,186 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-17 16:08:42,581 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-17 16:27:14,149 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-18 08:01:07,564 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-23 17:42:00,852 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140473917367792 for <Subprocess at 140473917367432 with name flask in state RUNNING> (stdout)> (<type 'exceptions.IOError'>:[Errno 29] Illegal seek [/usr/lib/python2.7/dist-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|handle_read_event|232] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|record_output|166] [/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py|_log|142] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|info|275] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|log|293] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|emit|186] [/usr/lib/python2.7/dist-packages/supervisor/loggers.py|doRollover|211])
2023-09-23 17:57:19,589 WARN received SIGTERM indicating exit request
2023-09-23 17:57:19,589 INFO waiting for celery, flask to die
2023-09-23 17:57:19,592 INFO stopped: flask (terminated by SIGTERM)
2023-09-23 17:57:21,594 INFO stopped: celery (exit status 0)
